### ISSUE TITLE
请问，有没有丢数据的可能

### ISSUE THREAD

**Issue by lamian3** [wu-sheng/DataCarrier#4]

**Comment by wu-sheng** [comment]
```java
public enum BufferStrategy {
    BLOCKING,
    OVERRIDE,
    IF_POSSIBLE
}
```

存在三种策略，第一种是不会丢数据的，第二种是直接覆盖未消费的数据，第三种是尝试写入，然后返回写入状态（skywalking使用这种）

**Comment by lamian3** [comment]
第一种策略，如果应用在run的时候，kill掉也不会丢么？有落磁盘？

**Comment by wu-sheng** [comment]
@momsbaby 不会落盘，datacarrier完全是针对轻量级内存异步处理准备的。

**Comment by lamian3** [comment]
@wu-sheng 哦，那就是如果应用kill掉，还是会丢数据的，明白了，谢谢。
