### ISSUE TITLE
关于可见性的问题

### ISSUE THREAD

**Issue by Cczzzz** [wu-sheng/DataCarrier#5]
生产者线程和消费者线程之间是否已经是放弃可见性了，这样不会出现有些数据延迟特别明显，或者队列已经写满但是消费者还无法可见。
我在代码中没有看见线程间可见性的保证。

**Comment by wu-sheng** [comment]
此库以完全合并到Apache SkyWalking中。我们没有特别加强线程可见性，如果你要提升，请提交PR到SkyWalking.
